### ISSUE TITLE
"undefined method" with any_instance.stub in RSpec 2.11

### ISSUE THREAD

**Issue by henrik** [rspec/rspec-expectations#164]
After upgrading from RSpec 2.10 to 2.11, this line fails every time:

```
ThinkingSphinx::Search.any_instance.stub(:error)
```

The error:

```
undefined method `dup' for class `ThinkingSphinx::Search'
/Users/henrik/.rvm/gems/ruby-1.9.3-p0-patched@foobar/gems/rspec-mocks-2.11.1/li‌​b/rspec/mocks/any_instance.rb:64:in `alias_method'
```

Someone else got a similar error but with `undefined method \`__rspec_original_dup' `:

http://stackoverflow.com/questions/11679987/rspec-any-instance-stub-causing-error-undefined-method-rspec-original-dup

Sorry not to provide more info. Just reporting for now, but might dig into it further later.
