### ISSUE TITLE
Test works fine in 2.10.0 but not in 2.11.0

### ISSUE THREAD

**Issue by move-git** [rspec/rspec-expectations#155]
The test below failed in rspec 2.11.0 but works fine in 2.10.0
  Any ideas?

Thanks in advance.

```
Failure/Error: expect { xhr :post, :unsubscribe, guid: "secret-guid" }.should change(Unsubscribe.where(:email => invite.email), :count).by(1)
 NoMethodError:
   undefined method `call' for #<RSpec::Expectations::ExpectationTarget:0x0000000a21b790>
```
