### ISSUE TITLE
it { should include foo } fails or provides unexpected output if foo.respond_to?(:description)

### ISSUE THREAD

**Issue by gregates** [rspec/rspec-expectations#260]
This is probably a pretty weird edge case, but here goes:

I have a kind of wrapper object that behaves like this (the details have been abstracted away for hopefully clearer presentation):

```
class Handler

  def initialize(feature)
    @feature = feature
  end

  def description
    @feature.description
  end
end
```

Now, it's normally the case that the kind of object passed into `@feature` responds to `:description`. But I had a test that looked like this:

```
describe "::all" do
  subject { Handler.all }

  it { should include Handler.new(Object.new) }
end
```

This passed when I was using v2.6, but after upgrading to 2.13 it started failing with a `NoMethodError: undefined method 'description'`. I was surprised by this, because instantiating a `Handler` should not call the `description` method. When I tried stubbing the Object.new with a `description` method that said "This shouldn't be here", I got a passing test that looked like:

```
FeatureHandler
  ::all
    should include This shouldn't be here
```

So it appears to me that what's going wrong is that the `to_word` method in `rspec-expectations/lib/rspec/matchers/pretty.rb` is using `respond_to?(:description)` not just to check that the argument responds to `:description`, but also (implicitly) as a duck-type check -- it's expecting that if the object does respond to `:description`, we'll have an object of type `RSpec::Core::Example` or some other rspec object. But obviously that assumption fails in my weird edge case!

I thought about submitting a patch along with this issue report but I'm not really sure what the correct fix is. More explicit type-checking? Differently named methods so that there's even less likelihood of unintended collisions?
